# Site settings
title: "Anderson Mamede | Blog"
description: Um blog sobre desenvolvimento web
baseurl: ""
url: "http://blog.andersonmamede.com.br"

# User settings
username: Anderson Mamede
user_title: Desenvolvedor Web/Mobile e (ex-)jogador de Tibia
user_description: Desenvolvedor Web/Mobile e (ex-)jogador de Tibia
email: mamede.anderson@gmail.com
twitter_username: andersonrmamede
github_username: AndersonMamede
gplus_username: 104244621006686851628
disqus_username: andersonmamede.disqus.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Início
    url: /
#  - title: Series
#    url: /series
  - title: Tags
    url: /tags
#  - title: About Me
#    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
